"""added search functionality

Revision ID: 063e0d1b0592
Revises: 30f191d4459d
Create Date: 2018-12-06 13:45:14.369016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063e0d1b0592'
down_revision = '30f191d4459d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reviews_user_id_fkey', 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('reviews_user_id_fkey', 'reviews', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
