"""added relationship

Revision ID: 9e489a8da788
Revises: f6f0556d31cc
Create Date: 2018-12-03 19:02:42.730796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e489a8da788'
down_revision = 'f6f0556d31cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'businesses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.drop_column('businesses', 'user_id')
    # ### end Alembic commands ###
